BloodBank/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace BloodBank.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About_Us()
        {
            return View();
        }
    }
}

BloodBank/Controllers/ContactController.cs
using BloodBank.Data;
using BloodBank.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BloodBank.Controllers
{
    public class ContactController : Controller
    {
        ApplicationDBContext db;
        public ContactController(ApplicationDBContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact_Us()
        {
            return View(new Communucation());
        }

        [HttpPost]
        public IActionResult Contact_Us(IFormCollection frm)
        {
            Communucation c = new Communucation() { };
            c.person_name = frm["name"].ToString();
            c.email = frm["email"].ToString();
            c.subject = frm["subject"].ToString();
            c.message = frm["message"].ToString();
            db.Communucations.Add(c);
            db.SaveChanges();
            
            return View();
        }
    }
}

BloodBank/Controllers/DonateController.cs
using BloodBank.Data;
using BloodBank.Models;
using Microsoft.AspNetCore.Mvc;

namespace BloodBank.Controllers
{
    public class DonateController : Controller
    {
        ApplicationDBContext db;
        public DonateController(ApplicationDBContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Donation()
        {
            return View(new Donors());
        }

        
        [HttpPost]
        public IActionResult Donation(IFormCollection frm)
        {
            Donors d = new Donors() { };
            d.donor_name = frm["name"].ToString();
            d.email = frm["email"].ToString();
            d.phone = frm["phone"].ToString();
            d.gender = frm["gender"].ToString();
            d.BloodType = frm["BloodType"].ToString();
            db.Donors.Add(d);
            db.SaveChanges();

            return View();
        }
    }
}

BloodBank/Controllers/NeedController.cs
using BloodBank.Data;
using BloodBank.Models;
using Microsoft.AspNetCore.Mvc;

namespace BloodBank.Controllers
{
    public class NeedController : Controller
    {
        ApplicationDBContext db;
        public NeedController(ApplicationDBContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult needs()
        {
            return View(new Needers());
        }

        [HttpPost]
        public IActionResult needs(IFormCollection frm)
        {
            Needers n = new Needers() { };
            n.needer_name = frm["name"].ToString();
            n.email = frm["email"].ToString();
            n.phone = frm["phone"].ToString();
            n.gender = frm["gender"].ToString();
            n.BloodType = frm["BloodType"].ToString();
            db.Needers.Add(n);
            db.SaveChanges();

            return View();
        }
    }
}

BloodBank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/favicon.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="~/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: Medilab
    * Updated: Mar 10 2023 with Bootstrap v5.2.3
    * Template URL: https://bootstrapmade.com/medilab-free-medical-bootstrap-theme/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <div id="topbar" class="d-flex align-items-center fixed-top">
        <div class="container d-flex justify-content-between">
            <div class="contact-info d-flex align-items-center">
                <i class="bi bi-envelope"></i> <a href="mailto:contact@LifeFoundation.com">contact@example.com</a>
                <i class="bi bi-phone"></i> +1 5589 55488 55
            </div>
            <div class="d-none d-lg-flex social-links align-items-center">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></i></a>
            </div>
        </div>
    </div>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top">
        <div class="container d-flex align-items-center">

            <h1 class="logo me-auto"><a href="index.html">Blood Bank</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html" class="logo me-auto"><img src="~/assets/img/logo.png" alt="" class="img-fluid"></a>-->

            <nav id="navbar" class="navbar order-last order-lg-0">
                <ul>
                    <li><a class="nav-link scrollto active" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a class="nav-link scrollto" asp-controller="About" asp-action="About_Us">About</a></li>
                   
                    <li><a class="nav-link scrollto" asp-controller="Contact" asp-action="Contact_Us">Contact</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

            <a asp-controller="Donate" asp-action="Donation" class="appointment-btn scrollto"><span class="d-none d-md-inline"> DONATE</a>
            <a asp-controller="Need" asp-action="needs" class="appointment-btn scrollto"><span class="d-none d-md-inline"> REQUIST</a>
        </div>
    </header><!-- End Header -->
    <!-- ======= Hero Section ======= -->
    <section id="hero" class="d-flex align-items-center">
        <div class="container">
            <h1>Welcome to the Life Bank</h1>
            <h2>A single drop of blood can make a huge difference</h2>
            <a asp-controller="About" asp-action="about" class="btn-get-started scrollto">Get Started</a>
        </div>
    </section><!-- End Hero -->


    <main id="main">

        <!-- ======= Why Us Section ======= -->
        <section id="why-us" class="why-us">
            <div class="container">

                <div class="row">
                    <div class="col-lg-4 d-flex align-items-stretch">
                        <div class="content">
                            <h3>Why Donate?</h3>
                            <p>
                                It helps people in need, and it helps people in your community.
                                When you give, others live. Donors, especially those who donate regularly,
                                keep our nation's blood supply stable. Although many people donate blood after disasters,
                                blood is needed every day of the year.
                            </p>

                        </div>
                    </div>


                </div>

            </div>
        </section><!-- End Why Us Section -->

        <main id="main">





            @RenderBody()





        </main><!-- End #main -->
        <!-- ======= Footer ======= -->
        <footer id="footer">

            <div class="footer-top">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-3 col-md-6 footer-contact">
                            <h3>Blood Bank</h3>
                            <p>
                                A108 AboBaker Street <br>
                                Assuit, NY 535022<br>
                                Egypt <br><br>
                                <strong>Phone:</strong> +1 5589 55488 55<br>
                                <strong>Email:</strong> info@example.com<br>
                            </p>
                        </div>

                        <div class="col-lg-2 col-md-6 footer-links">
                            <h4>Useful Links</h4>
                            <ul>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Home" asp-action="Index">Home</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="About" asp-action="About_Us">About us</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Contact" asp-action="Contact_Us">Contact</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Doctor" asp-action="doctor">Doctor</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Donate" asp-action="Donation">Donate</a></li>
                                <li><i class="bx bx-chevron-right"></i> <a asp-controller="Need" asp-action="needs">Requist</a></li>
                            </ul>
                        </div>



                    </div>
                </div>
            </div>

            <div class="container d-md-flex py-4">

                <div class="me-md-auto text-center text-md-start">
                    <div class="copyright">
                        &copy; Copyright <strong><span>Blood Bank</span></strong>. All Rights Reserved
                    </div>
                    
                </div>
                <div class="social-links text-center text-md-right pt-3 pt-md-0">
                    <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
                    <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
                    <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
                    <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
                    <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
                </div>
            </div>
        </footer><!-- End Footer -->

        <div id="preloader"></div>
        <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

        <!-- Vendor JS Files -->
        <script src="~/assets/vendor/purecounter/purecounter_vanilla.js"></script>
        <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="~/assets/vendor/glightbox/js/glightbox.min.js"></script>
        <script src="~/assets/vendor/swiper/swiper-bundle.min.js"></script>
        <script src="~/assets/vendor/php-email-form/validate.js"></script>

        <!-- Template Main JS File -->
        <script src="~/assets/js/main.js"></script>

</body>

</html>



@await RenderSectionAsync("Scripts", required: false)